POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1NTSIsImlkIjoiNjg5M2FkM2U0YzFiYTZlMmJjNDBiNGYyIiwiaWF0IjoxNzU0NTA5OTM1fQ.b47p8ZWKYflloqhHuVdYxojoXBlbuDBvQ4gdTh7BDrA

{
  "title": "Wish you were here",
  "author": "Pink Floyd",
  "url": "www.blogs.com",
  "likes": 4
}
